meta_product_name: "Ludigo"
meta_title: "Ludigo - Trouvez des activités et organisez votre planning"
meta_description: "Ludigo facilite la vie des animateurs de centres de loisirs en rassemblant la recherche d'activités et l'organisation des journées en une seule application."
meta_image: "cover-facebook.png" # should exist in `app/assets/images/`
